INSERT INTO product (id, name, description, price, quantity, status, fk_supplier) VALUES
	(1, 'Pepper - Green Thai', 'Optimized exuding encryption', 0.72, 29, 'morbi', 2),
	(2, 'Sobe - Lizard Fuel', 'Stand-alone eco-centric support', 118.7, 0, 'aliquet', 2),
	(3, 'Bread - Assorted Rolls', 'Managed heuristic benchmark', 440.13, 87, 'faucibus', 3),
	(4, 'Sword Pick Asst', 'Proactive clear-thinking function', 335.45, 76, 'semper', 10),
	(5, 'Venison - Ground', 'Organized coherent focus group', 194.12, 10, 'bibendum', 10),
	(6, 'Dates', 'Horizontal analyzing structure', 354.93, 68, 'maecenas', 9),
	(7, 'Sprouts - Corn', 'Diverse zero defect array', 169.8, 53, 'elementum', 10),
	(8, 'Soup - Boston Clam Chowder', 'Implemented encompassing core', 427.4, 6, 'aliquam', 1),
	(9, 'Soup - Knorr, Ministrone', 'Open-architected bottom-line benchmark', 468.93, 70, 'lobortis', 5),
	(10, 'Tomatoes - Vine Ripe, Red', 'Multi-layered client-server alliance', 35.34, 18, 'turpis', 10),
	(11, 'Pasta - Fettuccine, Egg, Fresh', 'Reactive high-level protocol', 34.14, 26, 'nulla', 4),
	(12, 'Cake - Bande Of Fruit', 'Fully-configurable zero defect Graphical User Interface', 477.41, 73, 'sed', 4),
	(13, 'Tea - Orange Pekoe', 'Multi-layered leading edge strategy', 428.05, 27, 'nec', 7),
	(14, 'Bread - Pumpernickel', 'Inverse intermediate time-frame', 414.63, 19, 'magna', 8),
	(15, 'Wine - Maipo Valle Cabernet', 'Total fresh-thinking migration', 48.96, 41, 'ullamcorper', 10),
	(16, 'Beans - Kidney, Red Dry', 'Function-based real-time budgetary management', 153.49, 46, 'quisque', 2),
	(17, 'Wine - Magnotta - Red, Baco', 'Persistent contextually-based ability', 347.46, 23, 'sollicitudin', 4),
	(18, 'Fiddlehead - Frozen', 'Streamlined client-driven leverage', 256.7, 6, 'magnis', 8),
	(19, 'Halibut - Whole, Fresh', 'Cloned modular policy', 14.8, 97, 'nam', 5),
	(20, 'Juice - Apple, 500 Ml', 'Centralized scalable ability', 452.34, 87, 'interdum', 4);